ALTER TABLE "Room"."Room"
	ADD COLUMN "Administrative Id" SERIAL,
	ADD COLUMN "Doctor Id" SERIAL,
	ADD COLUMN "Emergency Id" SERIAL,
	ADD COLUMN "Inpatient Id" SERIAL,
	ADD COLUMN "Outpatient Id" SERIAL,
	ADD COLUMN "Diagnosis Id" SERIAL,
	ADD COLUMN "Surgical Id" SERIAL,
	ADD COLUMN "Treatment Id" SERIAL,
	ADD COLUMN "Support Id" SERIAL,
	ADD COLUMN "Pharmacy Id" SERIAL,
	ADD COLUMN "Residential Id" SERIAL,
	ADD COLUMN "Visitor Id" SERIAL,
	ADD COLUMN "Utility Id" SERIAL,
	ADD COLUMN "Misc Id" SERIAL;
ALTER TABLE "Room"."Administrative"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Executive Level" INTEGER,
	ADD COLUMN "Department Id" SERIAL;
ALTER TABLE "Room"."Doctor"
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL;
ALTER TABLE "Room"."Emergency"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Capacity" INTEGER,
	ADD COLUMN "Availability" BOOLEAN,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Critical Level" INTEGER,
	ADD COLUMN "Description" TEXT;
ALTER TABLE "Room"."Inpatient"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Capacity" INTEGER,
	ADD COLUMN "Availability" BOOLEAN,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "INTEGERensive Care" BOOLEAN,
	ADD COLUMN "Description" TEXT;
ALTER TABLE "Room"."Outpatient"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Capacity" INTEGER,
	ADD COLUMN "Availability" BOOLEAN,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL;
ALTER TABLE "Room"."Diagnosis"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Capacity" INTEGER,
	ADD COLUMN "Availability" BOOLEAN,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Facilities List" TEXT[],
	ADD COLUMN "Description" TEXT;
ALTER TABLE "Room"."Surgical"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Availability" BOOLEAN,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Surgery Type" VARCHAR(255),
	ADD COLUMN "Attached Teaching Area" BOOLEAN;
ALTER TABLE "Room"."Treatment"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Capacity" INTEGER,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Availability" BOOLEAN,
	ADD COLUMN "Facilities List" TEXT[];
ALTER TABLE "Room"."Support"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Capacity" INTEGER,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL;
ALTER TABLE "Room"."Pharmacy"
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL;
ALTER TABLE "Room"."Residential"
	ADD COLUMN "Type" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Capacity" INTEGER,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL;
ALTER TABLE "Room"."Visitor"
	ADD COLUMN "Type" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Capacity" INTEGER,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL;
ALTER TABLE "Room"."Utility"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Floor" INTEGER,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Utility Type" INTEGER,
	ADD COLUMN "Utility Output Unit" NUMERIC(5, 2);
ALTER TABLE "Room"."Misc"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Type" VARCHAR(255),
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Capacity" INTEGER,
	ADD COLUMN "Area Unit" NUMERIC(5, 2);
ALTER TABLE "Consumable"."Consumable"
	ADD COLUMN "Pharmaceutical Id" SERIAL,
	ADD COLUMN "Medical Supplies Id" SERIAL;
ALTER TABLE "Consumable"."Pharmaceutical"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Quantity" INTEGER,
	ADD COLUMN "Purchase Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Expiration Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Pharmacy Id" SERIAL,
	ADD COLUMN "Brand" TEXT,
	ADD COLUMN "Type" VARCHAR(255),
	ADD COLUMN "Volume Unit" NUMERIC(5, 2),
	ADD COLUMN "Weight Unit" NUMERIC(5, 2),
	ADD COLUMN "Package Size Unit" NUMERIC(5, 2);
ALTER TABLE "Consumable"."Medical Supplies"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Quantity" INTEGER,
	ADD COLUMN "Purchase Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Expiration Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Pharmacy Id" SERIAL;
ALTER TABLE "Inventory"."Inventory"
	ADD COLUMN "Edible Id" SERIAL,
	ADD COLUMN "Medical Equipment Id" SERIAL,
	ADD COLUMN "Supplies Id" SERIAL,
	ADD COLUMN "Electronic Id" SERIAL,
	ADD COLUMN "Vehicle Id" SERIAL;
ALTER TABLE "Inventory"."Edible"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Purchase Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Expiration Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Quantity" INTEGER,
	ADD COLUMN "Room Id" SERIAL;
ALTER TABLE "Inventory"."Medical Equipment"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Purchase Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Expiration Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Availability" BOOLEAN,
	ADD COLUMN "Maintenance Schedule Id" SERIAL,
	ADD COLUMN "Maintenance Logs Id" SERIAL;
ALTER TABLE "Inventory"."Supplies"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Purchase Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Expiration Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "Inventory"."Electronic"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Purchase Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Expiration Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Medical" BOOLEAN;
ALTER TABLE "Inventory"."Vehicle"
	ADD COLUMN "Type" VARCHAR(255),
	ADD COLUMN "Purchase Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Availability" BOOLEAN,
	ADD COLUMN "Maintenance Schedule Id" SERIAL,
	ADD COLUMN "Maintenance Logs Id" SERIAL,
	ADD COLUMN "Model" TEXT,
	ADD COLUMN "Purpose" VARCHAR(255),
	ADD COLUMN "Capacity" INTEGER;
ALTER TABLE "Budget"."Budget"
	ADD COLUMN "Total Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Allocated Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Remaining Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Year" INTEGER,
	ADD COLUMN "Description" TEXT;
ALTER TABLE "Budget"."Department Budget"
	ADD COLUMN "Total Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Allocated Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Remaining Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Year" INTEGER,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Department Id" SERIAL;
ALTER TABLE "Budget"."Expense"
	ADD COLUMN "Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Type" VARCHAR(255),
	ADD COLUMN "Invoice Id" SERIAL,
	ADD COLUMN "Department Id" SERIAL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Cash Flow Id" SERIAL;
ALTER TABLE "Budget"."Compensations"
	ADD COLUMN "Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Type" VARCHAR(255),
	ADD COLUMN "Invoice Id" SERIAL,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Cash Flow Id" SERIAL;
ALTER TABLE "Budget"."Revenue"
	ADD COLUMN "Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Type" VARCHAR(255),
	ADD COLUMN "Invoice Id" SERIAL,
	ADD COLUMN "Department Id" SERIAL,
	ADD COLUMN "Cash Flow Id" SERIAL;
ALTER TABLE "Budget"."Cash Flow"
	ADD COLUMN "Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Balance" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Type" VARCHAR(255),
	ADD COLUMN "Invoice Id" SERIAL,
	ADD COLUMN "Record Editor Id" SERIAL,
	ADD COLUMN "Flow" VARCHAR(255);
ALTER TABLE "Management"."Board"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "Management"."Research Team"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Report Id" SERIAL,
	ADD COLUMN "Department Id" SERIAL;
ALTER TABLE "Management"."Department"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Room Id" SERIAL;
ALTER TABLE "Management"."Position"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Department Id" SERIAL,
	ADD COLUMN "PayScale" INTEGER,
	ADD COLUMN "Compensation" NUMERIC(8, 2) NOT NULL,
	ADD COLUMN "Clearance Level" INTEGER;
ALTER TABLE "Staff"."Staff"
	ADD COLUMN "Director Id" SERIAL,
	ADD COLUMN "Administration Id" SERIAL,
	ADD COLUMN "Doctor Id" SERIAL,
	ADD COLUMN "Nurse Id" SERIAL,
	ADD COLUMN "Medical Technician Id" SERIAL,
	ADD COLUMN "Therapist Id" SERIAL,
	ADD COLUMN "Clinical Support Id" SERIAL,
	ADD COLUMN "Non-Medical Support Id" SERIAL,
	ADD COLUMN "Pharmacy Id" SERIAL,
	ADD COLUMN "Transport Id" SERIAL,
	ADD COLUMN "Teacher Id" SERIAL,
	ADD COLUMN "Volunteer Id" SERIAL;
ALTER TABLE "Staff"."Director"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "Staff"."Administration"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Medical" BOOLEAN;
ALTER TABLE "Staff"."Doctor"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Qualifications" TEXT[],
	ADD COLUMN "Licenses" TEXT[],
	ADD COLUMN "Specializations" TEXT[];
ALTER TABLE "Staff"."Nurse"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Licenses" TEXT[],
	ADD COLUMN "Trainings" TEXT[];
ALTER TABLE "Staff"."Medical Technician"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Licenses" TEXT[];
ALTER TABLE "Staff"."Therapist"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Qualifications" TEXT[],
	ADD COLUMN "Licenses" TEXT[];
ALTER TABLE "Staff"."Clinical Support"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Licenses" TEXT[];
ALTER TABLE "Staff"."Non-Medical Support"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "Staff"."Pharmacy"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Licenses" TEXT[];
ALTER TABLE "Staff"."Transport"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Licenses" TEXT[];
ALTER TABLE "Staff"."Teacher"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Qualifications" TEXT[],
	ADD COLUMN "Trainings" TEXT[],
	ADD COLUMN "Specializations" TEXT[];
ALTER TABLE "Staff"."Volunteer"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Position Id" SERIAL,
	ADD COLUMN "Attendance Id" SERIAL,
	ADD COLUMN "Active" BOOLEAN,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "Profile"."Profile"
	ADD COLUMN "First Name" VARCHAR(255),
	ADD COLUMN "Last Name" VARCHAR(255),
	ADD COLUMN "Contact Number" VARCHAR(15),
	ADD COLUMN "Emergency Contact Number" VARCHAR(15),
	ADD COLUMN "Address 1" TEXT,
	ADD COLUMN "Address 2" TEXT,
	ADD COLUMN "Email" VARCHAR(30);
ALTER TABLE "Patient"."Patient"
	ADD COLUMN "Profile Id" SERIAL,
	ADD COLUMN "Inpatient" BOOLEAN NOT NULL;
ALTER TABLE "Patient"."Consent Form"
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Consent Form Id" SERIAL;
ALTER TABLE "Patient"."Prescription"
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Invoice Id" SERIAL;
ALTER TABLE "Patient"."Invoice"
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Invoice Id" SERIAL;
ALTER TABLE "Patient"."Lab Report"
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Lab Report Id" SERIAL;
ALTER TABLE "Patient"."Medical Record"
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Medical Record Id" SERIAL;
ALTER TABLE "Schedule"."Shift"
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Shift Name" VARCHAR(255);
ALTER TABLE "Schedule"."Schedule"
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Shift Id" SERIAL,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "General Id" SERIAL,
	ADD COLUMN "Appointment Id" SERIAL,
	ADD COLUMN "Emergency Id" SERIAL,
	ADD COLUMN "Maintenance Id" SERIAL,
	ADD COLUMN "Vehicle Id" SERIAL;
ALTER TABLE "Schedule"."General"
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL;
ALTER TABLE "Schedule"."Appointment"
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL;
ALTER TABLE "Schedule"."Emergency"
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL;
ALTER TABLE "Schedule"."Maintenance"
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL;
ALTER TABLE "Schedule"."Vehicle"
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Purpose" VARCHAR(255);
ALTER TABLE "Document"."Directive"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Report Id" SERIAL;
ALTER TABLE "Document"."Invoice"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Issue Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Payment Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Issuer Id" SERIAL,
	ADD COLUMN "Currency" VARCHAR(5),
	ADD COLUMN "Total Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Tax Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Issuer Name" VARCHAR(255),
	ADD COLUMN "Recipient Id" SERIAL,
	ADD COLUMN "Recipient Name" VARCHAR(255),
	ADD COLUMN "Payment Status" BOOLEAN;
ALTER TABLE "Document"."Invoice Expanded"
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Consumable Id" SERIAL,
	ADD COLUMN "Invoice Id" SERIAL;
ALTER TABLE "Document"."Prescription"
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Issuer Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Invoice Id" SERIAL;
ALTER TABLE "Document"."Prescription Expanded"
	ADD COLUMN "Consumable Id" SERIAL,
	ADD COLUMN "Prescription Id" SERIAL;
ALTER TABLE "Document"."Consent Form"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Report Id" SERIAL,
	ADD COLUMN "Consenter Name" VARCHAR(255),
	ADD COLUMN "Consenter Profile Id" SERIAL;
ALTER TABLE "Document"."Emergency Report"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Report Id" SERIAL,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Schedule Id" SERIAL,
	ADD COLUMN "Emergency Type" VARCHAR(255),
	ADD COLUMN "Surgery Type" VARCHAR(255),
	ADD COLUMN "Critical Level" INTEGER;
ALTER TABLE "Document"."Patient Medical Record"
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Schedule Id" SERIAL,
	ADD COLUMN "Inpatient" BOOLEAN NOT NULL,
	ADD COLUMN "Diagnosis" TEXT,
	ADD COLUMN "Treatment" TEXT,
	ADD COLUMN "Additional Notes" TEXT;
ALTER TABLE "Document"."Lab Report"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Test  Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Result Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Schedule Id" SERIAL;
ALTER TABLE "Document"."Report"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Issuer Id" SERIAL;
ALTER TABLE "Document"."Insurance"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Report Id" SERIAL,
	ADD COLUMN "Approval Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Policy Type" VARCHAR(255),
	ADD COLUMN "Holder Profile Id" SERIAL,
	ADD COLUMN "Provider Name" VARCHAR(255),
	ADD COLUMN "Provider Representative Name" VARCHAR(255),
	ADD COLUMN "Provider Representative Profile Id" SERIAL,
	ADD COLUMN "Coverage Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Premium Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Claim Limit" NUMERIC(12, 2),
	ADD COLUMN "Status" TEXT;
ALTER TABLE "Document"."Attendance"
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Schedule Id" SERIAL,
	ADD COLUMN "Attendance" BOOLEAN;
ALTER TABLE "Document"."Contracts"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Report Id" SERIAL,
	ADD COLUMN "Renew Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Contract Type" VARCHAR(255),
	ADD COLUMN "Status" TEXT,
	ADD COLUMN "Department Id" SERIAL,
	ADD COLUMN "Issuer Id" SERIAL,
	ADD COLUMN "Signee Id" SERIAL,
	ADD COLUMN "Payment Amount" NUMERIC(12, 2) NOT NULL,
	ADD COLUMN "Terms and Conditions Link" TEXT NOT NULL;
ALTER TABLE "Document"."Meeting Minutes"
	ADD COLUMN "Agenda" TEXT,
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Report Id" SERIAL,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Schedule Id" SERIAL;
ALTER TABLE "Document"."Medical Equipment Logs"
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Patient Id" SERIAL,
	ADD COLUMN "Report Id" SERIAL,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Schedule Id" SERIAL;
ALTER TABLE "Document"."Maintenance Logs"
	ADD COLUMN "Name" VARCHAR(255),
	ADD COLUMN "Document Link" TEXT NOT NULL,
	ADD COLUMN "Approved By Id" INTEGER NOT NULL,
	ADD COLUMN "Description" TEXT,
	ADD COLUMN "Start Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "End Date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN "Staff Id" SERIAL,
	ADD COLUMN "Report Id" SERIAL,
	ADD COLUMN "Room Id" SERIAL,
	ADD COLUMN "Inventory Id" SERIAL,
	ADD COLUMN "Schedule Id" SERIAL;
