ALTER TABLE `Room Room`
	ADD COLUMN `Administrative Id` INT,
	ADD COLUMN `Doctor Id` INT,
	ADD COLUMN `Emergency Id` INT,
	ADD COLUMN `Inpatient Id` INT,
	ADD COLUMN `Outpatient Id` INT,
	ADD COLUMN `Diagnosis Id` INT,
	ADD COLUMN `Surgical Id` INT,
	ADD COLUMN `Treatment Id` INT,
	ADD COLUMN `Support Id` INT,
	ADD COLUMN `Pharmacy Id` INT,
	ADD COLUMN `Residential Id` INT,
	ADD COLUMN `Visitor Id` INT,
	ADD COLUMN `Utility Id` INT,
	ADD COLUMN `Misc Id` INT;
ALTER TABLE `Room Administrative`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Executive Level` INT,
	ADD COLUMN `Department Id` INT;
ALTER TABLE `Room Doctor`
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT;
ALTER TABLE `Room Emergency`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Capacity` INT,
	ADD COLUMN `Availability` BIT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Critical Level` INT,
	ADD COLUMN `Description` TEXT;
ALTER TABLE `Room Inpatient`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Capacity` INT,
	ADD COLUMN `Availability` BIT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Intensive Care` BIT,
	ADD COLUMN `Description` TEXT;
ALTER TABLE `Room Outpatient`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Capacity` INT,
	ADD COLUMN `Availability` BIT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT;
ALTER TABLE `Room Diagnosis`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Capacity` INT,
	ADD COLUMN `Availability` BIT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Facilities List` JSON,
	ADD COLUMN `Description` TEXT;
ALTER TABLE `Room Surgical`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Availability` BIT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Surgery Type` VARCHAR(255),
	ADD COLUMN `Attached Teaching Area` BIT;
ALTER TABLE `Room Treatment`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Capacity` INT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Availability` BIT,
	ADD COLUMN `Facilities List` JSON;
ALTER TABLE `Room Support`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Capacity` INT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT;
ALTER TABLE `Room Pharmacy`
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT;
ALTER TABLE `Room Residential`
	ADD COLUMN `Type` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Capacity` INT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT;
ALTER TABLE `Room Visitor`
	ADD COLUMN `Type` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Capacity` INT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT;
ALTER TABLE `Room Utility`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Floor` INT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Utility Type` INT,
	ADD COLUMN `Utility Output Unit` DECIMAL(5, 2);
ALTER TABLE `Room Misc`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Type` VARCHAR(255),
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Capacity` INT,
	ADD COLUMN `Area Unit` DECIMAL(5, 2);
ALTER TABLE `Consumable Consumable`
	ADD COLUMN `Pharmaceutical Id` INT,
	ADD COLUMN `Medical Supplies Id` INT;
ALTER TABLE `Consumable Pharmaceutical`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Quantity` INT,
	ADD COLUMN `Purchase Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Expiration Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Pharmacy Id` INT,
	ADD COLUMN `Brand` TEXT,
	ADD COLUMN `Type` VARCHAR(255),
	ADD COLUMN `Volume Unit` DECIMAL(5, 2),
	ADD COLUMN `Weight Unit` DECIMAL(5, 2),
	ADD COLUMN `Package Size Unit` DECIMAL(5, 2);
ALTER TABLE `Consumable Medical Supplies`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Quantity` INT,
	ADD COLUMN `Purchase Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Expiration Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Pharmacy Id` INT;
ALTER TABLE `Inventory Inventory`
	ADD COLUMN `Edible Id` INT,
	ADD COLUMN `Medical Equipment Id` INT,
	ADD COLUMN `Supplies Id` INT,
	ADD COLUMN `Electronic Id` INT,
	ADD COLUMN `Vehicle Id` INT;
ALTER TABLE `Inventory Edible`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Purchase Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Expiration Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Quantity` INT,
	ADD COLUMN `Room Id` INT;
ALTER TABLE `Inventory Medical Equipment`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Purchase Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Expiration Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Availability` BIT,
	ADD COLUMN `Maintenance Schedule Id` INT,
	ADD COLUMN `Maintenance Logs Id` INT;
ALTER TABLE `Inventory Supplies`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Purchase Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Expiration Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Quantity` INT;
ALTER TABLE `Inventory Electronic`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Purchase Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Expiration Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Medical` BIT;
ALTER TABLE `Inventory Vehicle`
	ADD COLUMN `Type` VARCHAR(255),
	ADD COLUMN `Purchase Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Availability` BIT,
	ADD COLUMN `Maintenance Schedule Id` INT,
	ADD COLUMN `Maintenance Logs Id` INT,
	ADD COLUMN `Model` TEXT,
	ADD COLUMN `Purpose` VARCHAR(255),
	ADD COLUMN `Capacity` INT;
ALTER TABLE `Budget Budget`
	ADD COLUMN `Total Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Allocated Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Remaining Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Year` INT,
	ADD COLUMN `Description` TEXT;
ALTER TABLE `Budget Department Budget`
	ADD COLUMN `Total Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Allocated Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Remaining Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Year` INT,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Department Id` INT;
ALTER TABLE `Budget Expense`
	ADD COLUMN `Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Type` VARCHAR(255),
	ADD COLUMN `Invoice Id` INT,
	ADD COLUMN `Department Id` INT,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Cash Flow Id` INT;
ALTER TABLE `Budget Compensations`
	ADD COLUMN `Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Type` VARCHAR(255),
	ADD COLUMN `Invoice Id` INT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Cash Flow Id` INT;
ALTER TABLE `Budget Revenue`
	ADD COLUMN `Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Type` VARCHAR(255),
	ADD COLUMN `Invoice Id` INT,
	ADD COLUMN `Department Id` INT,
	ADD COLUMN `Cash Flow Id` INT;
ALTER TABLE `Budget Cash Flow`
	ADD COLUMN `Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Balance` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Type` VARCHAR(255),
	ADD COLUMN `Invoice Id` INT,
	ADD COLUMN `Record Editor Id` INT,
	ADD COLUMN `Flow` VARCHAR(255);
ALTER TABLE `Management Board`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Management Research Team`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Report Id` INT,
	ADD COLUMN `Department Id` INT;
ALTER TABLE `Management Department`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Room Id` INT;
ALTER TABLE `Management Position`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Department Id` INT,
	ADD COLUMN `PayScale` INT,
	ADD COLUMN `Compensation` DECIMAL(8, 2) NOT NULL,
	ADD COLUMN `Clearance Level` INT;
ALTER TABLE `Staff Staff`
	ADD COLUMN `Director Id` INT,
	ADD COLUMN `Administration Id` INT,
	ADD COLUMN `Doctor Id` INT,
	ADD COLUMN `Nurse Id` INT,
	ADD COLUMN `Medical Technician Id` INT,
	ADD COLUMN `Therapist Id` INT,
	ADD COLUMN `Clinical Support Id` INT,
	ADD COLUMN `Non-Medical Support Id` INT,
	ADD COLUMN `Pharmacy Id` INT,
	ADD COLUMN `Transport Id` INT,
	ADD COLUMN `Teacher Id` INT,
	ADD COLUMN `Volunteer Id` INT;
ALTER TABLE `Staff Director`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Staff Administration`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Medical` BIT;
ALTER TABLE `Staff Doctor`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Qualifications` JSON,
	ADD COLUMN `Licenses` JSON,
	ADD COLUMN `Specializations` JSON;
ALTER TABLE `Staff Nurse`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Licenses` JSON,
	ADD COLUMN `Trainings` JSON;
ALTER TABLE `Staff Medical Technician`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Licenses` JSON;
ALTER TABLE `Staff Therapist`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Qualifications` JSON,
	ADD COLUMN `Licenses` JSON;
ALTER TABLE `Staff Clinical Support`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Licenses` JSON;
ALTER TABLE `Staff Non-Medical Support`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Staff Pharmacy`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Licenses` JSON;
ALTER TABLE `Staff Transport`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Licenses` JSON;
ALTER TABLE `Staff Teacher`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Qualifications` JSON,
	ADD COLUMN `Trainings` JSON,
	ADD COLUMN `Specializations` JSON;
ALTER TABLE `Staff Volunteer`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Position Id` INT,
	ADD COLUMN `Attendance Id` INT,
	ADD COLUMN `Active` BIT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `Profile Profile`
	ADD COLUMN `First Name` VARCHAR(255),
	ADD COLUMN `Last Name` VARCHAR(255),
	ADD COLUMN `Contact Number` VARCHAR(15),
	ADD COLUMN `Emergency Contact Number` VARCHAR(15),
	ADD COLUMN `Address 1` TEXT,
	ADD COLUMN `Address 2` TEXT,
	ADD COLUMN `Email` VARCHAR(30);
ALTER TABLE `Patient Patient`
	ADD COLUMN `Profile Id` INT,
	ADD COLUMN `Inpatient` BIT NOT NULL;
ALTER TABLE `Patient Consent Form`
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Consent Form Id` INT;
ALTER TABLE `Patient Prescription`
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Invoice Id` INT;
ALTER TABLE `Patient Invoice`
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Invoice Id` INT;
ALTER TABLE `Patient Lab Report`
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Lab Report Id` INT;
ALTER TABLE `Patient Medical Record`
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Medical Record Id` INT;
ALTER TABLE `Schedule Shift`
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Shift Name` VARCHAR(255);
ALTER TABLE `Schedule Schedule`
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Shift Id` INT,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `General Id` INT,
	ADD COLUMN `Appointment Id` INT,
	ADD COLUMN `Emergency Id` INT,
	ADD COLUMN `Maintenance Id` INT,
	ADD COLUMN `Vehicle Id` INT;
ALTER TABLE `Schedule General`
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Patient Id` INT;
ALTER TABLE `Schedule Appointment`
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Patient Id` INT;
ALTER TABLE `Schedule Emergency`
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Patient Id` INT;
ALTER TABLE `Schedule Maintenance`
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Inventory Id` INT;
ALTER TABLE `Schedule Vehicle`
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Purpose` VARCHAR(255);
ALTER TABLE `Document Directive`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Report Id` INT;
ALTER TABLE `Document Invoice`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Issue Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Payment Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Issuer Id` INT,
	ADD COLUMN `Currency` VARCHAR(5),
	ADD COLUMN `Total Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Tax Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Issuer Name` VARCHAR(255),
	ADD COLUMN `Recipient Id` INT,
	ADD COLUMN `Recipient Name` VARCHAR(255),
	ADD COLUMN `Payment Status` BIT;
ALTER TABLE `Document Invoice Expanded`
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Consumable Id` INT,
	ADD COLUMN `Invoice Id` INT;
ALTER TABLE `Document Prescription`
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Issuer Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Invoice Id` INT;
ALTER TABLE `Document Prescription Expanded`
	ADD COLUMN `Consumable Id` INT,
	ADD COLUMN `Prescription Id` INT;
ALTER TABLE `Document Consent Form`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Report Id` INT,
	ADD COLUMN `Consenter Name` VARCHAR(255),
	ADD COLUMN `Consenter Profile Id` INT;
ALTER TABLE `Document Emergency Report`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Report Id` INT,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Schedule Id` INT,
	ADD COLUMN `Emergency Type` VARCHAR(255),
	ADD COLUMN `Surgery Type` VARCHAR(255),
	ADD COLUMN `Critical Level` INT;
ALTER TABLE `Document Patient Medical Record`
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Schedule Id` INT,
	ADD COLUMN `Inpatient` BIT NOT NULL,
	ADD COLUMN `Diagnosis` TEXT,
	ADD COLUMN `Treatment` TEXT,
	ADD COLUMN `Additional Notes` TEXT;
ALTER TABLE `Document Lab Report`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Test  Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Result Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Schedule Id` INT;
ALTER TABLE `Document Report`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Issuer Id` INT;
ALTER TABLE `Document Insurance`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Report Id` INT,
	ADD COLUMN `Approval Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Policy Type` VARCHAR(255),
	ADD COLUMN `Holder Profile Id` INT,
	ADD COLUMN `Provider Name` VARCHAR(255),
	ADD COLUMN `Provider Representative Name` VARCHAR(255),
	ADD COLUMN `Provider Representative Profile Id` INT,
	ADD COLUMN `Coverage Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Premium Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Claim Limit` DECIMAL(12, 2),
	ADD COLUMN `Status` TEXT;
ALTER TABLE `Document Attendance`
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Schedule Id` INT,
	ADD COLUMN `Attendance` BIT;
ALTER TABLE `Document Contracts`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Report Id` INT,
	ADD COLUMN `Renew Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Contract Type` VARCHAR(255),
	ADD COLUMN `Status` TEXT,
	ADD COLUMN `Department Id` INT,
	ADD COLUMN `Issuer Id` INT,
	ADD COLUMN `Signee Id` INT,
	ADD COLUMN `Payment Amount` DECIMAL(12, 2) NOT NULL,
	ADD COLUMN `Terms and Conditions Link` TEXT NOT NULL;
ALTER TABLE `Document Meeting Minutes`
	ADD COLUMN `Agenda` TEXT,
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Report Id` INT,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Schedule Id` INT;
ALTER TABLE `Document Medical Equipment Logs`
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Patient Id` INT,
	ADD COLUMN `Report Id` INT,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Schedule Id` INT;
ALTER TABLE `Document Maintenance Logs`
	ADD COLUMN `Name` VARCHAR(255),
	ADD COLUMN `Document Link` TEXT NOT NULL,
	ADD COLUMN `Approved By Id` INT NOT NULL,
	ADD COLUMN `Description` TEXT,
	ADD COLUMN `Start Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `End Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN `Staff Id` INT,
	ADD COLUMN `Report Id` INT,
	ADD COLUMN `Room Id` INT,
	ADD COLUMN `Inventory Id` INT,
	ADD COLUMN `Schedule Id` INT;
